version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: ./infra/php/dockerfile
    container_name: laravel-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
      - ./php.ini:/usr/local/etc/php/conf.d/custom.ini
    networks:
      - laravel-net
    depends_on:
      - db

  nginx:
    image: nginx:1.21-alpine
    container_name: laravel-nginx
    restart: unless-stopped
    ports:
      - "8082:80"
    volumes:
      - ./src:/var/www/html
      - ./infra/nginx:/etc/nginx/conf.d
    networks:
      - laravel-net
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: laravel-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: password
      MYSQL_USER: laravel_user
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - laravel-net

networks:
  laravel-net:
    driver: bridge

volumes:
  mysql-data:
    driver: local
